server:
  port: 7002


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-Registry: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      # 集群
      defaultZone: http://eureka7001.com:7001/eureka/